// Code generated by sqlgen. DO NOT EDIT.

package queries

import (
	"context"
	"database/sql"
	"time"
)

type SqlQueryer interface {
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
}

type SqlExecer interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
}

type CountTable1Result struct {
	NumRows int32
}

func CountTable1(ctx context.Context, db SqlQueryer) ([]CountTable1Result, error) {
	query := `
        SELECT
            count(*) AS num_rows
        FROM table_1;
    `

	rows, err := db.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}

	var results []CountTable1Result

	for rows.Next() {
		r := CountTable1Result{}
		err := rows.Scan(
			&r.NumRows,
		)
		if err != nil {
			return nil, err
		}
		results = append(results, r)
	}

	return results, rows.Err()
}

type GetJoinedResult struct {
	T1Id       int32
	ColA       sql.NullString
	ColB       string
	T2Id       int32
	SomeValue  sql.NullFloat64
	OtherValue []byte
}

func GetJoined(ctx context.Context, db SqlQueryer) ([]GetJoinedResult, error) {
	query := `
        SELECT 
            t1.id t1_id,
            col_a,
            col_b,
            t2.id t2_id,
            some_value,
            other_value
        FROM
            table_1 t1
            JOIN table_2 t2 ON
                t1.id=t2.ref_1
            JOIN table_3 t3 ON
                t1.id=t3.ref_1
        ORDER BY t1.id
        LIMIT 10;
    `

	rows, err := db.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}

	var results []GetJoinedResult

	for rows.Next() {
		r := GetJoinedResult{}
		err := rows.Scan(
			&r.T1Id,
			&r.ColA,
			&r.ColB,
			&r.T2Id,
			&r.SomeValue,
			&r.OtherValue,
		)
		if err != nil {
			return nil, err
		}
		results = append(results, r)
	}

	return results, rows.Err()
}

type GetTable1Result struct {
	Id   int32
	ColA sql.NullString
	ColB string
}

func GetTable1(ctx context.Context, db SqlQueryer) ([]GetTable1Result, error) {
	query := `
        SELECT * FROM table_1;
    `

	rows, err := db.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}

	var results []GetTable1Result

	for rows.Next() {
		r := GetTable1Result{}
		err := rows.Scan(
			&r.Id,
			&r.ColA,
			&r.ColB,
		)
		if err != nil {
			return nil, err
		}
		results = append(results, r)
	}

	return results, rows.Err()
}

type GetTable4Result struct {
	Id      string
	Created time.Time
	Updated sql.NullTime
}

func GetTable4(ctx context.Context, db SqlQueryer) ([]GetTable4Result, error) {
	query := `
        SELECT * FROM table_4;
    `

	rows, err := db.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}

	var results []GetTable4Result

	for rows.Next() {
		r := GetTable4Result{}
		err := rows.Scan(
			&r.Id,
			&r.Created,
			&r.Updated,
		)
		if err != nil {
			return nil, err
		}
		results = append(results, r)
	}

	return results, rows.Err()
}

type GetTable5Result struct {
	Id    int32
	Words []string
}

func GetTable5(ctx context.Context, db SqlQueryer) ([]GetTable5Result, error) {
	query := `
        SELECT * FROM table_5;
    `

	rows, err := db.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}

	var results []GetTable5Result

	for rows.Next() {
		r := GetTable5Result{}
		err := rows.Scan(
			&r.Id,
			&r.Words,
		)
		if err != nil {
			return nil, err
		}
		results = append(results, r)
	}

	return results, rows.Err()
}

type InsertTable1Arg struct {
	Id   int32
	ColA sql.NullString
	ColB string
}

func InsertTable1(ctx context.Context, db SqlExecer, arg InsertTable1Arg) error {
	query := `
        INSERT INTO table_1
        VALUES (
            $1,
            $2,
            $3
        );
    `

	_, err := db.ExecContext(ctx, query,
		arg.Id,
		arg.ColA,
		arg.ColB,
	)

	return err
}

type InsertTable4Arg struct {
	Id      string
	Created time.Time
	Updated sql.NullTime
}

func InsertTable4(ctx context.Context, db SqlExecer, arg InsertTable4Arg) error {
	query := `
        INSERT INTO table_4
            (id, created, updated)
        VALUES
            ($1, $2, $3);
    `

	_, err := db.ExecContext(ctx, query,
		arg.Id,
		arg.Created,
		arg.Updated,
	)

	return err
}

type InsertTable5Arg struct {
	Id    int32
	Words []string
}

func InsertTable5(ctx context.Context, db SqlExecer, arg InsertTable5Arg) error {
	query := `
        INSERT INTO table_5 (id, words)
        VALUES ($1, $2);
    `

	_, err := db.ExecContext(ctx, query,
		arg.Id,
		arg.Words,
	)

	return err
}

type QueryJoinedArg struct {
	Msg string
	Val float64
}

type QueryJoinedResult struct {
	T1Id      int32
	ColA      sql.NullString
	SomeValue sql.NullFloat64
}

func QueryJoined(ctx context.Context, db SqlQueryer, arg QueryJoinedArg) ([]QueryJoinedResult, error) {
	query := `
        SELECT
            t1.id t1_id,
            col_a,
            some_value
        FROM
            table_1 t1
            JOIN table_2 t2
                ON t1.id=t2.ref_1
        WHERE
            col_b = $1 AND
            some_value > $2;
    `

	rows, err := db.QueryContext(ctx, query,
		arg.Msg,
		arg.Val,
	)
	if err != nil {
		return nil, err
	}

	var results []QueryJoinedResult

	for rows.Next() {
		r := QueryJoinedResult{}
		err := rows.Scan(
			&r.T1Id,
			&r.ColA,
			&r.SomeValue,
		)
		if err != nil {
			return nil, err
		}
		results = append(results, r)
	}

	return results, rows.Err()
}

