// Code generated by sqlgen. DO NOT EDIT.

package queries

import (
	"context"
	"database/sql"
)

type SqlQueryer interface {
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
}

type SqlExecer interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
}

type GetUserAndItemsArg struct {
	Email string
}

type GetUserAndItemsResult struct {
	Username sql.NullString
	Name     string
	Rating   sql.NullInt32
}

func GetUserAndItems(ctx context.Context, db SqlQueryer, arg GetUserAndItemsArg) ([]GetUserAndItemsResult, error) {
	query := `
        SELECT
            u.username,
            i.name,
            i.rating
        FROM
            users u
                LEFT JOIN user_items ui ON u.id=ui.user
                LEFT JOIN items i ON ui.item=i.id
        WHERE
            u.email = ?;
    `

	rows, err := db.QueryContext(ctx, query,
		arg.Email,
	)
	if err != nil {
		return nil, err
	}

	var results []GetUserAndItemsResult

	for rows.Next() {
		r := GetUserAndItemsResult{}
		err := rows.Scan(
			&r.Username,
			&r.Name,
			&r.Rating,
		)
		if err != nil {
			return nil, err
		}
		results = append(results, r)
	}

	return results, rows.Err()
}

