/*
 * File generated by sqlgen. Do not edit.
 */

export interface Dispatcher<TResult> {
    (query: string): Promise<TResult[]>;
}

export type GetTable1Result = {
    colA: string | null;
    colB: string;
    id: number;
};

export async function getTable1(
    dispatch: Dispatcher<GetTable1Result>,
): Promise<GetTable1Result[]> {
    const query = `
        SELECT * FROM table_1;
    `;

    return dispatch(query);
}

