use crate::{core::NamedQuery, error::CodegenError};

pub mod typescript;

pub trait Codegen {
    fn codegen(&self, queries: &[NamedQuery]) -> Result<String, CodegenError>;

    fn header(&self) -> &'static str {
        "File generated by sqlgen. Do not edit."
    }
}
