/*
 * File generated by sqlgen. Do not edit.
 */

export interface Dispatcher {
    (query: string, args?: unknown[]): Promise<{
        keys: string[];
        rows: unknown[][];
    }>;
}

function mapRows<TResult>(keys: string[], rows: unknown[][]): TResult[] {
    const out = Array(rows.length)
    for (let i = 0; i < out.length; i++) {
        const row = rows[i];
        out[i] = Object.fromEntries(pairs(keys, row));
    }
    return out as TResult[];
}

function pairs<T, U>(xs: T[], ys: U[]): [T, U][] {
    const out = Array(xs.length)
    for (let i = 0; i < out.length; i++) {
        out[i] = [xs[i], ys[i]];
    }
    return out;
}

export type GetJoinedResult = {
    t1Id: number;
    colA: string | null;
    colB: string;
    t2Id: number;
    someValue: number | null;
    otherValue: ArrayBuffer | null;
};

export async function getJoined(
    dispatch: Dispatcher,
): Promise<GetJoinedResult[]> {
    const query = `
        SELECT 
            t1.id t1_id,
            col_a,
            col_b,
            t2.id t2_id,
            some_value,
            other_value
        FROM
            table_1 t1
            JOIN table_2 t2 ON
                t1.id=t2.ref_1
            JOIN table_3 t3 ON
                t1.id=t3.ref_1
        ORDER BY t1.id
        LIMIT 10;
    `;

    const result = await dispatch(query);
    return mapRows<GetJoinedResult>(result.keys, result.rows);
}

export type GetTable1Result = {
    colA: string | null;
    colB: string;
    id: number;
};

export async function getTable1(
    dispatch: Dispatcher,
): Promise<GetTable1Result[]> {
    const query = `
        SELECT * FROM table_1;
    `;

    const result = await dispatch(query);
    return mapRows<GetTable1Result>(result.keys, result.rows);
}

export type InsertTable1Arg = {
    id: number;
    colA: string;
    colB: string;
};

export async function insertTable1(
    dispatch: Dispatcher,
    arg: InsertTable1Arg,
): Promise<void> {
    const query = `
        INSERT INTO table_1
        VALUES (
            ?,
            ?,
            ?
        );
    `;

    await dispatch(query, [
        arg.id,
        arg.colA,
        arg.colB,
    ]);
}

export type QueryJoinedArg = {
    msg: string;
    val: number;
};

export type QueryJoinedResult = {
    t1Id: number;
    colA: string | null;
    someValue: number | null;
};

export async function queryJoined(
    dispatch: Dispatcher,
    arg: QueryJoinedArg,
): Promise<QueryJoinedResult[]> {
    const query = `
        SELECT
            t1.id t1_id,
            col_a,
            some_value
        FROM
            table_1 t1
            JOIN table_2 t2
                ON t1.id=t2.ref_1
        WHERE
            col_b = ? AND
            some_value > ?;
    `;

    const result = await dispatch(query, [
        arg.msg,
        arg.val,
    ]);
    return mapRows<QueryJoinedResult>(result.keys, result.rows);
}

